
const C = (key,type,name,desc,nullable)=>({key,type,name,desc,nullable});
const pk=(type,name,desc)=>C('PK',type,name,desc,false);
const fk=(type,name,desc,nullable=true)=>C('FK',type,name,desc,nullable);
const uk=(type,name,desc)=>C('UK',type,name,desc,false);
const col=(type,name,desc,nullable=false)=>C('',type,name,desc,nullable);
const nul=(type,name,desc)=>C('',type,name,desc,true);

const HC_TABLES = {
  HOSPITALS:{schema:'hc',desc:'Multi-tenancy root — every other table scopes to hospital_id.',cols:[
    pk('UUID','hospital_id'),
    uk('VARCHAR','short_code','e.g. AIIMS-DEL, APOLLO-MUM'),
    col('VARCHAR','name'),
    col('VARCHAR','type','TERTIARY / PRIVATE / GOVT'),
    col('BOOLEAN','nabh_accredited'),
    nul('VARCHAR','rohini_id','Indian insurance registration ID'),
    nul('VARCHAR','address'),
    nul('VARCHAR','phone'),
    col('TIMESTAMPTZ','created_at'),
  ]},
  DEPARTMENTS:{schema:'hc',desc:'Clinical departments within a hospital.',cols:[
    pk('UUID','dept_id'),
    fk('UUID','hospital_id','hospitals',false),
    col('VARCHAR','name','Cardiology, ICU, Medicine'),
    col('VARCHAR','code','CARD, ICU, MED, SURG'),
    col('BOOLEAN','is_active'),
  ]},
  WARDS:{schema:'hc',desc:'Physical wards — CCU, General Ward, ICU, HDU, Emergency.',cols:[
    pk('UUID','ward_id'),
    fk('UUID','hospital_id','hospitals',false),
    fk('UUID','dept_id','departments',false),
    col('VARCHAR','name','e.g. CCU, General Ward 4B'),
    col('VARCHAR','ward_type','CCU / GW / ICU / HDU / EMERGENCY'),
    col('INT','capacity','total bed count'),
    col('BOOLEAN','is_active'),
  ]},
  BEDS:{schema:'hc',desc:'Individual beds. current_admission_id is live occupant FK.',cols:[
    pk('UUID','bed_id'),
    fk('UUID','ward_id','wards',false),
    col('VARCHAR','bed_number','CCU-01, GW-12'),
    col('VARCHAR','status','available / occupied / maintenance'),
    fk('UUID','current_admission_id','admissions — live occupant, nullable'),
  ]},
  STAFF:{schema:'hc',desc:'All hospital personnel. License number for NABH MN-4 compliance.',cols:[
    pk('UUID','staff_id'),
    fk('UUID','hospital_id','hospitals',false),
    fk('UUID','dept_id','departments',false),
    fk('UUID','ward_id','wards — primary posting',true),
    col('VARCHAR','full_name'),
    col('VARCHAR','role','staff_nurse / charge_nurse / resident / attending / admin_staff / cmo / billing_staff'),
    uk('VARCHAR','hospital_email'),
    nul('VARCHAR','license_no','MCI or Nursing Council registration'),
    col('TEXT','password_hash'),
    nul('TEXT','session_token'),
    col('BOOLEAN','is_active'),
    col('TIMESTAMPTZ','created_at'),
    col('TIMESTAMPTZ','updated_at'),
  ]},
  PATIENTS:{schema:'hc',desc:'Patient master — lifetime identity record, one per real person.',cols:[
    pk('VARCHAR','uhid','HOSP-YYYY-NNNNNNN format'),
    fk('UUID','hospital_id','hospitals',false),
    col('VARCHAR','full_name'),
    col('DATE','dob'),
    col('CHAR','sex','M / F / O'),
    nul('VARCHAR','contact'),
    col('VARCHAR','insurance_type','Ayushman_Bharat / CGHS / ESI / Private / None'),
    col('TIMESTAMPTZ','created_at'),
  ]},
  ADMISSIONS:{schema:'hc',desc:'Per-hospitalization record. admission_id is the universal cross-schema key.',cols:[
    pk('UUID','admission_id','UNIVERSAL KEY — travels through ews.* and discharge_ai.*'),
    fk('VARCHAR','uhid','patients',false),
    fk('UUID','hospital_id','hospitals',false),
    fk('UUID','ward_id','wards',false),
    fk('UUID','bed_id','beds',false),
    fk('UUID','primary_doctor_id','staff',false),
    col('VARCHAR','admission_type','EMERGENCY / ELECTIVE / TRANSFER_IN'),
    col('VARCHAR','status','admitted / in_ccu / transferred_to_gw / discharge_pending / discharged'),
    col('TIMESTAMPTZ','admitted_at'),
    nul('TIMESTAMPTZ','discharged_at'),
    col('TIMESTAMPTZ','created_at'),
    col('TIMESTAMPTZ','updated_at'),
  ]},
  DOCTOR_PATIENT_ASSIGNMENTS:{schema:'hc',desc:'Multi-doctor assignments per admission. unassigned_at IS NULL = currently active.',cols:[
    pk('UUID','assignment_id'),
    fk('UUID','admission_id','admissions',false),
    fk('UUID','doctor_id','staff',false),
    col('VARCHAR','assignment_type','PRIMARY / COVERING / CONSULTANT'),
    col('TIMESTAMPTZ','assigned_at'),
    nul('TIMESTAMPTZ','unassigned_at','NULL means currently active'),
  ]},
  WARD_TRANSFERS:{schema:'hc',desc:'ADT log for every ward move (CCU to GW, inter-ward, etc.).',cols:[
    pk('UUID','transfer_id'),
    fk('UUID','admission_id','admissions',false),
    fk('UUID','from_ward_id','wards',false),
    fk('UUID','to_ward_id','wards',false),
    col('VARCHAR','transfer_type','CCU_TO_GW / GW_TO_CCU / INTER_WARD'),
    nul('INT','news2_at_transfer','NEWS2 score snapshot at time of transfer'),
    fk('UUID','approved_by','staff',true),
    col('VARCHAR','status','pending / approved / completed / cancelled'),
    col('TIMESTAMPTZ','requested_at'),
    nul('TIMESTAMPTZ','completed_at'),
  ]},
  HIS_PATIENT_SYNC:{schema:'hc',desc:'Tracks ADT feed sync status from Hospital Information System.',cols:[
    pk('VARCHAR','sync_id'),
    fk('VARCHAR','uhid','patients',false),
    col('VARCHAR','his_system_name','HIS vendor name'),
    col('VARCHAR','sync_status','success / failed / pending'),
    col('TIMESTAMPTZ','last_synced_at'),
    nul('TEXT','error_message'),
  ]},
  INSURANCE_POLICIES:{schema:'hc',desc:'One patient can hold multiple policies (Ayushman Bharat + private, etc.).',cols:[
    pk('UUID','policy_id'),
    fk('VARCHAR','uhid','patients',false),
    col('VARCHAR','provider','Ayushman Bharat, Star Health, CGHS'),
    col('VARCHAR','policy_number'),
    col('DECIMAL','coverage_percent'),
    col('DECIMAL','deductible'),
    col('DECIMAL','co_pay_percent'),
    col('DATE','effective_date'),
    col('DATE','expiry_date'),
    col('BOOLEAN','is_active'),
  ]},
  PRE_AUTH_REQUESTS:{schema:'hc',desc:'Insurance pre-authorisation before or during admission.',cols:[
    pk('UUID','preauth_id'),
    fk('UUID','admission_id','admissions',false),
    fk('UUID','insurance_policy_id','insurance_policies',false),
    col('DECIMAL','estimated_cost'),
    col('VARCHAR','status','pending / approved / denied / expired'),
    nul('VARCHAR','approval_number'),
    nul('DATE','valid_until'),
    col('TIMESTAMPTZ','requested_at'),
    nul('TIMESTAMPTZ','decided_at'),
  ]},
  COST_LOOKUPS:{schema:'hc',desc:'Hospital-specific ICD-10 cost table with age and comorbidity adjustments.',cols:[
    pk('UUID','cost_id'),
    fk('UUID','hospital_id','hospitals',false),
    col('VARCHAR','diagnosis_code','ICD-10 code'),
    col('VARCHAR','diagnosis_label'),
    col('DECIMAL','base_cost'),
    col('DECIMAL','age_adjustment','percent per decade'),
    col('DECIMAL','comorbidity_factor'),
    col('VARCHAR','ward_tier','CCU / ICU / GW / HDU'),
    col('TIMESTAMPTZ','effective_from'),
  ]},
  NOTIFICATIONS:{schema:'hc',desc:'Push notification log for all clinical alerts across both services.',cols:[
    pk('UUID','notification_id'),
    fk('UUID','recipient_staff_id','staff',false),
    fk('UUID','admission_id','admissions',true),
    col('VARCHAR','type','transfer_ready / escalation_pending / billing_alert / drug_flag / sla_breach'),
    col('TEXT','message'),
    col('BOOLEAN','is_read'),
    col('TIMESTAMPTZ','sent_at'),
    nul('TIMESTAMPTZ','read_at'),
  ]},
  AUDIT_LOGS:{schema:'hc',desc:'NABH MN-4 + DPDPA compliant append-only audit trail. Never updated.',cols:[
    pk('BIGSERIAL','log_id'),
    fk('UUID','actor_staff_id','staff',false),
    fk('UUID','admission_id','admissions',true),
    col('VARCHAR','action_type','CREATE / UPDATE / DELETE / ACCESS / SIGN / ESCALATE'),
    col('VARCHAR','entity_table'),
    col('VARCHAR','entity_id'),
    nul('JSONB','old_values'),
    nul('JSONB','new_values'),
    nul('VARCHAR','ip_address'),
    nul('VARCHAR','request_id'),
    col('TIMESTAMPTZ','ts'),
  ]},
  DE_IDENTIFICATION_MAPPING:{schema:'hc',desc:'Maps real UHID to de-id code for DPDPA-compliant research exports.',cols:[
    pk('UUID','mapping_id'),
    fk('VARCHAR','uhid','patients',false),
    col('VARCHAR','de_id','used in MIMIC or research exports'),
    nul('VARCHAR','request_purpose'),
    fk('UUID','requested_by','staff',false),
    col('TIMESTAMPTZ','created_at'),
    nul('TIMESTAMPTZ','expires_at'),
  ]},
};

const EWS_TABLES = {
  VITALS_TIMESERIES:{schema:'ew',desc:'4-hour bucketed vitals. 12 fields — richest vitals schema across all 3 source architectures.',cols:[
    pk('BIGSERIAL','id'),
    fk('UUID','admission_id','hospital_core.admissions',false),
    col('TIMESTAMPTZ','chart_time','4-hour bucket window'),
    col('NUMERIC','heart_rate','bpm'),
    col('NUMERIC','resp_rate','breaths per min'),
    col('NUMERIC','spo2','percent'),
    col('NUMERIC','sbp','mmHg systolic'),
    col('NUMERIC','dbp','mmHg diastolic'),
    col('NUMERIC','temperature','Celsius'),
    col('CHAR','consciousness','AVPU scale: A / V / P / U'),
    col('VARCHAR','air_or_oxygen','Air or Oxygen'),
    nul('NUMERIC','urine_output','mL'),
    nul('NUMERIC','fluid_balance','mL per 24h'),
    nul('NUMERIC','weight_kg','daily weigh-in'),
    fk('UUID','recorded_by','hospital_core.staff — NABH attribution',false),
    col('TIMESTAMPTZ','recorded_at'),
  ]},
  LAB_EVENTS:{schema:'ew',desc:'10-biomarker cardiology-calibrated lab panel. MIMIC itemid mapping for ETL.',cols:[
    pk('BIGSERIAL','id'),
    fk('UUID','admission_id','hospital_core.admissions',false),
    col('TIMESTAMPTZ','chart_time'),
    nul('NUMERIC','potassium','mmol/L — itemid 50971'),
    nul('NUMERIC','creatinine','mg/dL — itemid 50912'),
    nul('NUMERIC','lactate','mmol/L — itemid 50813'),
    nul('NUMERIC','inr','itemid 51237'),
    nul('NUMERIC','egfr','CKD-EPI mL/min'),
    nul('NUMERIC','alt','U/L — itemid 50861'),
    nul('NUMERIC','bnp','pg/mL — itemids 50963, 51921 — DCM key marker'),
    nul('NUMERIC','troponin','ng/mL — itemid 51003'),
    nul('NUMERIC','sodium','mmol/L — itemid 50983'),
    nul('NUMERIC','hemoglobin','g/dL — itemid 51222'),
    fk('UUID','recorded_by','hospital_core.staff',false),
    col('TIMESTAMPTZ','recorded_at'),
  ]},
  MEDICATIONS:{schema:'ew',desc:'Active medication list per admission. Indian generic and brand names.',cols:[
    pk('BIGSERIAL','id'),
    fk('UUID','admission_id','hospital_core.admissions',false),
    col('VARCHAR','med_name','Indian generic or brand name'),
    nul('VARCHAR','dose'),
    nul('VARCHAR','frequency','OD / BD / TID / PRN / Q8H'),
    col('VARCHAR','route','PO / IV / SC / IM'),
    fk('UUID','prescribed_by','hospital_core.staff',false),
    col('TIMESTAMPTZ','prescribed_at'),
    col('BOOLEAN','is_active'),
  ]},
  DRUG_LAB_RULES:{schema:'ew',desc:'Database-driven drug-lab interaction rules. hospital_id NULL = global rule.',cols:[
    pk('UUID','rule_id'),
    fk('UUID','hospital_id','hospital_core.hospitals — NULL = global rule',true),
    col('VARCHAR','rule_name','e.g. Hyperkalemia + ACE Inhibitor'),
    col('VARCHAR','trigger_drug'),
    col('VARCHAR','trigger_lab'),
    col('NUMERIC','lab_threshold'),
    col('VARCHAR','comparator','gt / lt / gte / lte'),
    col('VARCHAR','severity','CRITICAL / WARNING / INFO'),
    col('VARCHAR','recommended_action','hold / reduce / monitor / notify'),
    col('TEXT','clinical_rationale'),
    col('VARCHAR','guideline_source','CDSCO / ICMR / ESC / FDA'),
    col('INT','version'),
    col('DATE','effective_date'),
    col('BOOLEAN','is_active'),
  ]},
  DRUG_LAB_FLAGS:{schema:'ew',desc:'Fired instances of drug-lab rules. T1/T2/T3 severity tiers from Professor ERD.',cols:[
    pk('UUID','flag_id'),
    fk('UUID','admission_id','hospital_core.admissions',false),
    fk('UUID','rule_id','drug_lab_rules',false),
    col('VARCHAR','severity','T1 critical / T2 warning / T3 info'),
    nul('VARCHAR','trigger_drug_value'),
    nul('NUMERIC','trigger_lab_value'),
    col('VARCHAR','recommended_action'),
    fk('UUID','actioned_by','hospital_core.staff — nullable until actioned',true),
    nul('TEXT','justification'),
    nul('VARCHAR','cosigned_by_name','NABH DL2 co-sign requirement'),
    col('VARCHAR','status','active / acknowledged / resolved / overridden'),
    col('TIMESTAMPTZ','flagged_at'),
    nul('TIMESTAMPTZ','actioned_at'),
  ]},
  ESCALATIONS:{schema:'ew',desc:'NEWS2-triggered escalation events. Full FSM with NABH SLA auto-flag.',cols:[
    pk('BIGSERIAL','id'),
    fk('UUID','admission_id','hospital_core.admissions',false),
    col('SMALLINT','news2_score'),
    col('VARCHAR','level','nurse / doctor / code_blue'),
    fk('UUID','escalated_by','hospital_core.staff',false),
    fk('UUID','attending_id','hospital_core.staff',true),
    nul('TEXT','observations'),
    nul('TEXT','interventions'),
    col('VARCHAR','status','active / pending_charge_ack / charge_acked / attending_notified / resolved / false_alarm / timeout'),
    col('BOOLEAN','false_alarm'),
    nul('TEXT','false_alarm_reason','dropdown options feed EWD model'),
    col('BOOLEAN','sla_breached','NABH SLA auto-flag'),
    col('TIMESTAMPTZ','escalated_at'),
    nul('TIMESTAMPTZ','acknowledged_at'),
    nul('TIMESTAMPTZ','resolved_at'),
    fk('UUID','resolved_by','hospital_core.staff',true),
    nul('TEXT','resolution_notes'),
    nul('TIMESTAMPTZ','reescalated_at'),
  ]},
  EWS_EVENTS:{schema:'ew',desc:'ML trend events — EWMA composite scores, model confidence, top contributing signals.',cols:[
    pk('UUID','id'),
    fk('UUID','admission_id','hospital_core.admissions',false),
    col('VARCHAR','event_type','NEWS2_RISING / TREND_ALERT / STEP_DOWN_ELIGIBLE / DCM_DECOMPENSATION'),
    col('NUMERIC','trend_score','EWMA composite'),
    col('NUMERIC','ml_confidence','0 to 100'),
    nul('JSONB','top_signals','array of param, direction, contribution objects'),
    col('VARCHAR','status','pending / actioned / dismissed'),
    col('TIMESTAMPTZ','detected_at'),
    fk('UUID','actioned_by','hospital_core.staff',true),
  ]},
  DCM_ASSESSMENTS:{schema:'ew',desc:'Dilated Cardiomyopathy structured assessment. NYHA class, LVEF, BNP at admission.',cols:[
    pk('UUID','id'),
    fk('UUID','admission_id','hospital_core.admissions',false),
    col('SMALLINT','nyha_class','1 to 4'),
    nul('NUMERIC','ef_percent','LVEF percent from echo'),
    nul('NUMERIC','baseline_weight_kg','at admission'),
    nul('NUMERIC','bnp_admission','pg/mL at admission'),
    col('SMALLINT','edema_grade','0 to 3'),
    fk('UUID','assessed_by','hospital_core.staff',false),
    col('TIMESTAMPTZ','assessed_at'),
  ]},
  FLUID_BALANCE:{schema:'ew',desc:'8-hour and 24-hour fluid balance records. Daily weight for fluid-overload trend.',cols:[
    pk('UUID','id'),
    fk('UUID','admission_id','hospital_core.admissions',false),
    col('INT','period_hours','8 or 24'),
    nul('NUMERIC','intake_ml','IV plus oral'),
    nul('NUMERIC','urine_ml'),
    nul('NUMERIC','drain_ml'),
    nul('NUMERIC','net_balance_ml','computed field'),
    nul('NUMERIC','daily_weight_kg'),
    fk('UUID','recorded_by','hospital_core.staff',false),
    col('TIMESTAMPTZ','recorded_at'),
  ]},
  TRANSFER_REQUESTS:{schema:'ew',desc:'Step-down CCU to GW requests. Multi-step approval with 5-criteria checklist gate.',cols:[
    pk('UUID','id'),
    fk('UUID','admission_id','hospital_core.admissions',false),
    fk('UUID','from_ward_id','hospital_core.wards',false),
    fk('UUID','to_ward_id','hospital_core.wards',false),
    fk('UUID','requested_by','hospital_core.staff — staff nurse',false),
    col('INT','news2_at_submit','NEWS2 score at submission'),
    col('INT','stable_window_hours','hours of stability before submission'),
    nul('JSONB','checklist_json','5 step-down criteria auto-populated'),
    col('BOOLEAN','vitals_fresh','chart_time within last 45 minutes'),
    fk('UUID','charge_approved_by','hospital_core.staff — head nurse',true),
    fk('UUID','attending_signed_by','hospital_core.staff',true),
    col('VARCHAR','status','pending_charge / charge_approved / attending_review / approved / rejected / completed'),
    nul('TEXT','rejection_reason'),
    col('TIMESTAMPTZ','submitted_at'),
    nul('TIMESTAMPTZ','decided_at'),
    nul('TIMESTAMPTZ','completed_at'),
  ]},
};

const DAI_TABLES = {
  ACTIVE_PATIENTS:{schema:'da',desc:'Bridge table: links MIMIC-IV hadm_id to hospital_core admission_id. Master hub for all ap_* clinical tables.',cols:[
    pk('BIGINT','hadm_id','MIMIC-IV legacy admission ID'),
    fk('UUID','admission_id','hospital_core.admissions — integration key',true),
    col('VARCHAR','data_fetch_status','pending / fetching / fetched / partial / failed'),
    col('VARCHAR','status','active / data_ready / summary_generated / signed_off / archived'),
    col('VARCHAR','discharge_type','Standard / LAMA / DAMA / Death / Referral'),
    col('CHAR','gender'),col('SMALLINT','anchor_age'),
    nul('VARCHAR','race'),nul('VARCHAR','insurance'),
    nul('VARCHAR','admission_type'),
    nul('TIMESTAMPTZ','admit_time'),nul('TIMESTAMPTZ','discharge_time'),
    nul('NUMERIC','los_days'),
    nul('VARCHAR','primary_diagnosis_code'),nul('TEXT','admitting_diagnosis'),
    fk('UUID','assigned_doctor_id','hospital_core.staff',true),
    nul('NUMERIC','nli_score','NLI entailment score'),
    nul('VARCHAR','claim_verification_status'),
    fk('UUID','signed_by','hospital_core.staff',true),
    nul('TIMESTAMPTZ','signed_at'),
    col('TIMESTAMPTZ','created_at'),col('TIMESTAMPTZ','updated_at'),
  ]},
  APP_ENCOUNTERS:{schema:'da',desc:'Workflow tracking record for each discharge summary generation cycle.',cols:[
    pk('UUID','id'),
    fk('BIGINT','hadm_id','active_patients',false),
    fk('UUID','admission_id','hospital_core.admissions',true),
    col('VARCHAR','status','Pending Ingestion / Processing / Ready for Review / Signed Off / Amendment Requested'),
    col('VARCHAR','complexity','Low / Medium / High'),
    fk('UUID','assigned_to','hospital_core.staff',true),
    col('INT','version','revision count'),
    nul('TIMESTAMPTZ','last_accessed_at'),
    col('TIMESTAMPTZ','created_at'),col('TIMESTAMPTZ','updated_at'),
  ]},
  APP_SUMMARIES:{schema:'da',desc:'Generated discharge summary. NLI entailment score for hallucination detection.',cols:[
    pk('UUID','id'),
    fk('UUID','encounter_id','app_encounters',false),
    col('BIGINT','hadm_id'),
    col('TEXT','content','full summary text blob'),
    nul('TEXT','clinical_context','RAG context chunks used in generation'),
    nul('NUMERIC','nli_score','0.0 to 1.0 entailment score'),
    nul('VARCHAR','claim_verification_status'),
    fk('UUID','signed_by','hospital_core.staff',true),
    nul('TIMESTAMPTZ','signed_at'),
    col('TIMESTAMPTZ','created_at'),col('TIMESTAMPTZ','updated_at'),
  ]},
  DISCHARGE_SECTIONS:{schema:'da',desc:'Per-section NABH tracking — 15 sections with individual confidence scores and edit audit. New from Professor ERD.',cols:[
    pk('UUID','section_id'),
    fk('UUID','summary_id','app_summaries',false),
    col('SMALLINT','section_number','1 to 15 NABH sections'),
    col('VARCHAR','section_name','Presenting Complaint, Medications, etc.'),
    col('TEXT','ai_content','AI-generated content'),
    nul('TEXT','edited_content','doctor-edited version'),
    col('NUMERIC','confidence_score','0.0 to 1.0'),
    fk('UUID','edited_by','hospital_core.staff',true),
    nul('TEXT','edit_reason'),
    nul('TIMESTAMPTZ','edited_at'),
  ]},
  DISCHARGE_AMENDMENTS:{schema:'da',desc:'Amendment workflow: section rejection triggers regeneration cycle. New from Professor ERD.',cols:[
    pk('UUID','amendment_id'),
    fk('UUID','summary_id','app_summaries — version being amended',false),
    fk('UUID','new_summary_id','app_summaries — regenerated version',true),
    fk('UUID','rejected_by','hospital_core.staff',false),
    col('TEXT','rejection_reason'),
    nul('TEXT','sections_rejected','JSON array of section numbers'),
    col('VARCHAR','status','pending_regen / regenerating / ready / signed'),
    col('TIMESTAMPTZ','requested_at'),
    nul('TIMESTAMPTZ','resolved_at'),
  ]},
  BILLING:{schema:'da',desc:'Cost estimation linked to ICD-10 lookups and insurance coverage. New from Professor ERD.',cols:[
    pk('UUID','billing_id'),
    fk('UUID','admission_id','hospital_core.admissions',false),
    fk('UUID','cost_lookup_id','hospital_core.cost_lookups',false),
    fk('UUID','insurance_policy_id','hospital_core.insurance_policies',true),
    col('DECIMAL','estimated_cost'),
    nul('DECIMAL','final_amount'),
    nul('DECIMAL','insurance_covered'),
    nul('DECIMAL','patient_payable'),
    nul('DECIMAL','variance_percent'),
    nul('TEXT','variance_reason'),
    col('VARCHAR','status','draft / finalized / submitted / settled'),
    col('TIMESTAMPTZ','created_at'),
    nul('TIMESTAMPTZ','finalized_at'),
  ]},
  APP_UPLOADED_FILES:{schema:'da',desc:'GCS file tracking for all 18 clinical data types uploaded per patient.',cols:[
    pk('UUID','id'),
    fk('BIGINT','hadm_id','active_patients',false),
    fk('UUID','encounter_id','app_encounters',true),
    col('VARCHAR','file_type','labs / meds / notes / diagnoses / procedures / icu / microbiology / transfers'),
    col('VARCHAR','file_name'),
    col('BIGINT','file_size'),
    col('TEXT','gcs_path','Google Cloud Storage URI'),
    col('VARCHAR','indexed_status','pending / indexed / failed'),
    fk('UUID','uploaded_by','hospital_core.staff',false),
    col('TIMESTAMPTZ','uploaded_at'),
  ]},
  APP_CLINICAL_ROWS:{schema:'da',desc:'Raw CSV row storage for RAG re-indexing without re-upload.',cols:[
    pk('BIGSERIAL','id'),
    fk('BIGINT','hadm_id','active_patients',false),
    col('VARCHAR','file_type'),
    fk('UUID','file_id','app_uploaded_files',false),
    col('JSONB','rows','array of CSV row objects'),
    col('TIMESTAMPTZ','created_at'),
  ]},
  ERROR_LOG:{schema:'da',desc:'3-tier AI accuracy framework. Tier 3 rolling 7-day rate = NABH launch gate. Unique to this design.',cols:[
    pk('SERIAL','id'),
    col('BIGINT','hadm_id'),
    nul('VARCHAR','summary_version','v1.0, v1.1'),
    col('VARCHAR','nabh_section','s1 through s15'),
    col('SMALLINT','error_tier','1 = minor, 2 = moderate, 3 = critical'),
    col('TEXT','ai_output'),
    col('TEXT','correct_value'),
    col('VARCHAR','error_category','medication_dose / diagnosis / hallucination / formatting / other'),
    col('BOOLEAN','source_present','was data present in source documents?'),
    fk('UUID','attending_id','hospital_core.staff',true),
    col('TIMESTAMPTZ','created_at'),
  ]},
  APP_AUDIT_LOG:{schema:'da',desc:'Discharge AI specific audit trail. Append-only.',cols:[
    pk('BIGSERIAL','id'),
    col('VARCHAR','action','80-char label'),
    nul('BIGINT','hadm_id'),
    fk('UUID','user_id','hospital_core.staff',false),
    nul('JSONB','details'),
    col('TIMESTAMPTZ','created_at'),
  ]},
  APP_SETTINGS:{schema:'da',desc:'Singleton hospital-level configuration for the discharge summary AI.',cols:[
    pk('INT','id','always 1 — singleton constraint'),
    fk('UUID','hospital_id','hospital_core.hospitals',false),
    col('VARCHAR','hospital_name'),
    nul('VARCHAR','wing'),nul('VARCHAR','city'),
    nul('VARCHAR','mci_nabh_number'),
    nul('TEXT','footer_disclaimer'),
    col('NUMERIC','nli_entailment_threshold','default 0.5'),
    col('SMALLINT','k_retrieved_chunks','default 5'),
    col('NUMERIC','dense_retrieval_weight','default 0.7'),
    col('BOOLEAN','auto_notify_doctor'),
    col('TIMESTAMPTZ','updated_at'),
  ]},
};

// Key MIMIC tables shown individually; rest grouped
const MIMIC_TABLES = {
  AP_ADMISSIONS:{schema:'da',desc:'MIMIC-IV patient + admission demographics. Source: mimiciv_hosp.admissions + patients.',cols:[
    pk('BIGINT','hadm_id'),col('INT','subject_id'),
    col('TIMESTAMPTZ','admittime'),col('TIMESTAMPTZ','dischtime'),nul('TIMESTAMPTZ','deathtime'),
    col('VARCHAR','admission_type'),col('VARCHAR','insurance'),col('VARCHAR','race'),
    col('CHAR','gender'),col('SMALLINT','anchor_age'),nul('DATE','dod'),
  ]},
  AP_LABEVENTS:{schema:'da',desc:'Laboratory results — high volume, 500-5000 rows per admission. Includes LOINC codes.',cols:[
    pk('BIGINT','labevent_id'),col('BIGINT','hadm_id'),
    col('INT','itemid'),col('VARCHAR','label'),col('VARCHAR','fluid'),
    col('TIMESTAMPTZ','charttime'),col('VARCHAR','value'),col('NUMERIC','valuenum'),
    col('VARCHAR','valueuom'),col('NUMERIC','ref_range_lower'),col('NUMERIC','ref_range_upper'),
    nul('VARCHAR','flag','abnormal or NULL'),nul('VARCHAR','loinc_code'),
  ]},
  AP_CHARTEVENTS:{schema:'da',desc:'Vitals + ICU monitoring — largest table, 5000+ rows per patient. Indexed by (hadm_id, charttime DESC).',cols:[
    pk('BIGSERIAL','id'),col('BIGINT','hadm_id'),col('INT','stay_id'),
    col('INT','itemid'),col('VARCHAR','label'),col('VARCHAR','category'),
    col('TIMESTAMPTZ','charttime'),col('NUMERIC','valuenum'),col('VARCHAR','valueuom'),
    nul('SMALLINT','warning'),
  ]},
  AP_PRESCRIPTIONS:{schema:'da',desc:'Prescribed medications. Drug codes: formulary_drug_cd, GSN, NDC.',cols:[
    pk('BIGSERIAL','id'),col('BIGINT','hadm_id'),
    col('TIMESTAMPTZ','starttime'),col('TIMESTAMPTZ','stoptime'),
    col('VARCHAR','drug'),col('VARCHAR','dose_val_rx'),col('VARCHAR','dose_unit_rx'),col('VARCHAR','route'),
  ]},
  'AP_OTHER_x14':{schema:'da',desc:'14 additional MIMIC-IV tables: ap_diagnoses, ap_procedures, ap_drgcodes, ap_microbiologyevents, ap_icustays, ap_transfers, ap_services, ap_pharmacy, ap_poe, ap_omr, ap_procedureevents, ap_datetimeevents, ap_inputevents, ap_outputevents.',cols:[
    col('BIGSERIAL','id','(or source PK)'),
    fk('BIGINT','hadm_id','active_patients',false),
    col('TEXT','clinical_fields','varies per table — see MIMIC-IV v3.1 schema'),
  ]},
};

const CMP_ROWS = [
  ['Schema namespace isolation','✗ Prefix only (app_*, ews_*, ap_*)','✗ Single flat schema','✓ 3 PG schemas','★ 3 schemas with cross-schema FK support','crs','crs','chk','best'],
  ['Patient vs. Admission separation','✗ active_patients conflates both','✓ patients + encounters','✓ patients + admissions','★ patients (UHID) + admissions (UUID) + bridge for MIMIC compat','crs','chk','chk','best'],
  ['Universal cross-system key','✗ hadm_id is MIMIC-specific','~ encounter_id per schema only','✓ admission_id UUID','★ admission_id UUID + hadm_id compat column','crs','prt','chk','best'],
  ['Multi-tenancy','✗ No hospital table','✓ hospital_configs','✓ HOSPITALS table','★ HOSPITALS as root entity, all tables FK-scoped','crs','chk','chk','best'],
  ['Nursing role modelling','✗ Staff names as free-text strings','~ users table includes nurse role','✓ STAFF with staff_nurse / charge_nurse','★ 7 roles + license_no + ward posting FK','crs','prt','chk','best'],
  ['Vital signs richness','✓ 12 fields, 4-hour buckets','✗ Only 4 fields (spo2, rr, hr, bp)','~ 6 fields — no temp or fluid_balance','★ All 12 current fields + recorded_by FK + admission_id FK','chk','crs','prt','best'],
  ['Lab event biomarkers','✓ 10 biomarkers incl. cardiology panel','✗ No dedicated lab table','~ 6 biomarkers','★ All 10 current biomarkers + recorded_by FK','chk','crs','prt','best'],
  ['Section-level NABH discharge','✗ Summary as single TEXT blob','★ discharge_sections with confidence + edit audit','✗ Not modelled','★ discharge_sections + discharge_amendments with rejection FSM','crs','best','crs','best'],
  ['Discharge amendment versioning','✗ No amendment workflow','✓ discharge_amendments with parent_version_id','✗ Not modelled','★ status FSM + section-level rejection list','crs','chk','crs','best'],
  ['Drug-lab rules in database','~ YAML only — not DB-driven','✓ drug_lab_rules + drug_lab_flags','~ Not explicitly modelled','★ drug_lab_rules (hospital_id scope, versioned, guideline_source) + T1/T2/T3 flags','prt','chk','prt','best'],
  ['Insurance and TPA workflow','✗ No insurance tables','✓ insurance_policies + pre_auth_requests','✗ Not modelled','★ insurance_policies (multi-policy per patient) + pre_auth_requests + billing linkage','crs','chk','crs','best'],
  ['Billing and cost estimation','~ DRG fields in active_patients only','✓ billing + cost_lookups','✗ Not modelled','★ billing (estimated vs final, variance) + cost_lookups (age and comorbidity adjustments)','prt','chk','crs','best'],
  ['Ward and Bed hierarchy','✗ Ward is a VARCHAR string','✗ No ward or bed tables','✓ WARDS + BEDS tables','★ WARDS (type CCU/GW/ICU) + BEDS (status + live admission FK)','crs','crs','chk','best'],
  ['Step-down transfer workflow','~ Simple pending / approved / rejected','~ transfer_events multi-step but no checklist','✓ checklist_json + charge_approved_by','★ Full FSM: pending_charge to charge_approved to attending_review + vitals_fresh gate','prt','prt','chk','best'],
  ['DCM-specific clinical tables','~ NYHA, LVEF as columns on active_patients','✗ Not modelled','✓ dcm_assessments table','★ dcm_assessments + fluid_balance as separate 8/24h period table','prt','crs','chk','best'],
  ['ML trend event tracking','✗ Not in DB','✗ Not modelled','✓ ews_events table','★ ews_events with top_signals JSONB + ml_confidence + FSM status','crs','crs','chk','best'],
  ['Push notifications','✗ No notification table','✓ notifications table','✗ Not modelled','★ notifications (transfer_ready, escalation_pending, drug_flag, sla_breach)','crs','chk','crs','best'],
  ['HIS integration tracking','✗ No HIS sync tracking','✓ his_patient_sync','✗ Not modelled','★ his_patient_sync with error_message for failed syncs','crs','chk','crs','best'],
  ['Comprehensive audit trail','~ app_audit_log action + hadm_id + details JSONB','✓ audit_logs old/new values, entity_table, IP','~ Inherits current app_audit_log','★ hospital_core.audit_logs (actor, entity, old/new JSON, IP, request_id) + dai audit log','prt','chk','prt','best'],
  ['MIMIC-IV clinical data','✓ 18 ap_* tables, 500K+ rows per patient','✗ No equivalent','~ Represented as simplified ap_clinical_tables','★ All 18 ap_* tables preserved in discharge_ai schema + app_clinical_rows for uploads','chk','crs','prt','best'],
  ['AI accuracy tracking 3-tier','✓ error_log tier1/2/3, per-section, rolling 7d view','✗ Not modelled','✗ Not modelled','★ error_log preserved — unique to this design, no other architecture has it','chk','crs','crs','best'],
  ['File and GCS tracking','✓ app_uploaded_files + app_clinical_rows','✗ Not modelled','✗ Not modelled','★ Both tables preserved in discharge_ai schema','chk','crs','crs','best'],
  ['De-identification mapping','✗ MIMIC de-id implicit only','✓ de_identification_mapping','✗ Not modelled','★ de_identification_mapping with request_purpose + expires_at (DPDPA retention)','crs','chk','crs','best'],
  ['Performance indexing strategy','✓ 50+ indexes incl. partial indexes for queue views','✗ Not specified','✗ Not specified','★ All current indexing patterns carried forward + new FK column indexes','chk','crs','crs','best'],
];

// ── RENDER ────────────────────────────────────────────────────────────────────



function generateErDiagram(tables) {
  let er = "erDiagram\n";
  for (const [name, def] of Object.entries(tables)) {
    er += `    ${name} {\n`;
    for (const c of def.cols) {
      let typeStr = (c.type || 'string').replace(/ /g, '_');
      let nameStr = c.name || 'id';
      let keyStr = c.key ? ` ${c.key}` : '';
      let commentStr = c.desc ? ` "${c.desc.replace(/"/g, "'")}"` : (c.nullable ? ` "nullable"` : "");
      er += `        ${typeStr} ${nameStr}${keyStr}${commentStr}\n`;
    }
    er += `    }\n`;
  }
  return er;
}

console.log("--- HC ---");
console.log(generateErDiagram(HC_TABLES));
console.log("--- EWS ---");
console.log(generateErDiagram(EWS_TABLES));
console.log("--- DAI ---");
console.log(generateErDiagram({...DAI_TABLES, ...MIMIC_TABLES}));
