-- Migration 015: Unified Staff Auth
-- Extends app_users to cover EWS roles (Ward Nurse, Charge Nurse, GW Nurse, Resident)
-- so both Ashmit's discharge AI and Sabari's EWS ward monitor share one auth table.
-- Safe to re-run: uses IF NOT EXISTS / DO blocks throughout.

-- 1. Drop the old role CHECK constraint (name is auto-generated by PostgreSQL)
DO $$
DECLARE
    cname text;
BEGIN
    SELECT conname INTO cname
    FROM pg_constraint
    WHERE conrelid = 'app_users'::regclass
      AND contype = 'c'
      AND pg_get_constraintdef(oid) LIKE '%role%'
    LIMIT 1;
    IF cname IS NOT NULL THEN
        EXECUTE 'ALTER TABLE app_users DROP CONSTRAINT ' || quote_ident(cname);
    END IF;
END $$;

-- 2. Add new constraint with all roles (discharge AI + EWS ward monitor)
ALTER TABLE app_users
    ADD CONSTRAINT app_users_role_check CHECK (role IN (
        'Doctor',
        'Admin Staff',
        'Billing Staff',
        'Super Admin',
        'Ward Nurse',
        'Charge Nurse',
        'GW Nurse',
        'Resident'
    ));

-- 3. Add ward_assignment column (nullable — only relevant for EWS roles)
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS ward_assignment VARCHAR(50) DEFAULT NULL;

-- 4. Seed demo EWS users (plain-text passwords — auto-upgraded to bcrypt on first login)
--    Uses ON CONFLICT DO NOTHING so re-running is safe.
INSERT INTO app_users (id, hospital_email, role, full_name, password_hash, ward_assignment, is_active, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'rekha.devi@foqal.in',     'Ward Nurse',   'Nurse Rekha Devi',    'WardNurse@2026',   'Ward 4B/4C',   TRUE, NOW(), NOW()),
    (gen_random_uuid(), 'leena.kurup@foqal.in',    'Charge Nurse', 'Sister Leena Kurup',  'ChargeNurse@2026', 'Ward 4B/4C',   TRUE, NOW(), NOW()),
    (gen_random_uuid(), 'prathima.m@foqal.in',     'GW Nurse',     'Nurse Prathima M',    'GWNurse@2026',     'General Ward', TRUE, NOW(), NOW()),
    (gen_random_uuid(), 'dr.anand@foqal.in',       'Resident',     'Dr. Anand Sharma',    'Resident@2026',    'Ward 4B/4C',   TRUE, NOW(), NOW())
ON CONFLICT (hospital_email, role) DO NOTHING;

-- 5. Index on ward_assignment for fast ward-roster queries
CREATE INDEX IF NOT EXISTS idx_users_ward ON app_users (ward_assignment) WHERE ward_assignment IS NOT NULL;
